[package]
name = "json2bson"
version = "0.1.0"
authors = ["Patrick Meredith <pmeredit@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.46"
bson = "0.14.0"
